cluster:
  name: vultr-rke2-cluster
  kubernetesVersion: v1.31.9+rke2r1
  cloudCredentialSecretName: vultr-creds

nodepool:
  - name: vultr-controlplane
    quantity: 1
    etcd: true
    controlplane: true
    worker: false
  - name: vultr-worker
    quantity: 2
    etcd: false
    controlplane: false
    worker: true


vultr:
  region: ewr
  plan: vc2-1c-2gb
  osId: "1743"
  sshUser: root
  sshKeyIds: []
  tags: []
  backups: false
  ddosProtection: false
  ipv6: false
  enableVPC: false
  vpcIds: []
  firewallGroupId: ""
  isoId: ""
  appId: 0
  imageId: ""
  ipxeChainUrl: ""
  startupScriptId: ""
  snapshotId: ""
  cloudInitUserData: ""
  floatingIPv4Id: ""
  sendActivationEmail: false
