apiVersion: rke-machine-config.cattle.io/v1
kind: VultrConfig
metadata:
  name: {{ .Values.cluster.name }}-nodes
  namespace: fleet-default
spec:
  region: {{ .Values.vultr.region }}
  plan: {{ .Values.vultr.plan }}
  osId: {{ .Values.vultr.osId }}
  sshUser: {{ .Values.vultr.sshUser }}

