{{- range .Values.cluster.rkeConfig.machinePools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VultrConfig
metadata:
  name: {{ .name }}
  namespace: fleet-default
spec:
{{ toYaml .providerConfig | indent 2 }}
---
{{- end }}
